{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ethiack-beacon.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ethiack-beacon.labels" . | nindent 4 }}
type: Opaque
stringData:
  ETHIACK_API_KEY: {{ .Values.credentials.apiKey | required "credentials.apiKey is required" | quote }}
  ETHIACK_API_SECRET: {{ .Values.credentials.apiSecret | required "credentials.apiSecret is required" | quote }}
{{- end }}
