apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ethiack-beacon-state
  namespace: ethiack
  labels:
    app.kubernetes.io/name: ethiack-beacon
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: standard  # uncomment and set if your cluster has no default StorageClass
  resources:
    requests:
      storage: 500Mi
